import re
from django.core.exceptions import ValidationError


def phone_number_validator(value):
    ...


